<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AlDia</AssemblyName>
    <RootNamespace>AlDia</RootNamespace>
    <Product>Al Día</Product>
    <Version>0.1.0</Version>
    <Company>juanitreque</Company>
    <Copyright>MIT License</Copyright>
    <ApplicationIcon>Recursos/AlDia.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <SatelliteResourceLanguages>es;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Recursos/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="QuestPDF" Version="2026.9.1" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AlDia.Core/AlDia.Core.csproj" />
  </ItemGroup>

</Project>
